### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ismail-codinglab** [JorgenVatle/xsolla#1]
![image](https://user-images.githubusercontent.com/48755937/58507376-ef819a00-8191-11e9-9f29-9eed6e75facb.png)

**Comment by ismail-codinglab** [comment]
using v8.12.0

**Comment by ismail-codinglab** [comment]
pls use module.exports

**Comment by JorgenVatle** [comment]
Oops, sorry. I'll address that first thing in the morning. 👍

For now you should be able to use `require('xsolla').default`

**Comment by ismail-codinglab** [comment]
Thank you sir

**Comment by JorgenVatle** [comment]
Fixed in https://github.com/JorgenVatle/xsolla/commit/c6da05f2e17bdc6755922be34d04aaefff7964c7. 

Opted to stick with default exports as it is my understanding that it is the future of JavaScript modules.

**Comment by ismail-codinglab** [comment]
Why not both?

Nodejs is based on commonjs... So you're telling me you don't support nodejs but need an es6 or typescript transpiler?

**Comment by JorgenVatle** [comment]
The package should come with a precompiled CommonJS version. You just need to import Xsolla using `require('xsolla').default` instead of just `require('xsolla')` like you might be used to.

This is to keep support for TypeScript types exported in the same entryfile. Besides, the latest versions of NodeJS should have support for the new `import Xsolla from 'xsolla'` syntax.

If you do know a better solution given the structure of the package, I'd be more than open to refactor accordingly. 👍
